d_bporte_test_users:
    path:     /dbase/getall
    defaults: { _controller: DBporteBundle:DBase:getall }

d_bporte_test_new_user:
    path:     /dbase/adduser
    defaults: { _controller: DBporteBundle:DBase:adduser }

d_bporte_view_put_user:
    path:     /dbase/put{id}
    defaults: { _controller: DBporteBundle:DBase:putuser }


