<?php

namespace DB\porteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeRepository extends EntityRepository
{
}
